name: Build and Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install required dependencies for compiling F90
      run: sudo apt-get install gfortran libopenblas-dev libfftw3-dev libhdf5-dev libnfft3-dev

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Check Fortran build
      # Add commands here to build your Fortran code.
      # run: |
      #     gfortran -o my_program src/f90_routines/my_program.f90
      #     ./my_program

    - name: Test with `pytest`
      run: |
        python -m pytest -sv tests

    # Add Fortran specific testing here in the future
    # - name: Fortran Tests
    #   run: |
    #       ./fortran_tests
