name: Build, Test, and Deploy MkDocs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install required dependencies for compiling F90
      run: sudo apt-get install gfortran libopenblas-dev libfftw3-dev libhdf5-dev libnfft3-dev

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: pycodestyle
      run: |
        python -m pycodestyle --ignore=E501,E701,E731 *parsers tests
    - name: pylint
      run: |
        python -m pylint *parsers tests
    - name: mypy
      run: |
        python -m mypy --ignore-missing-imports --follow-imports=silent --no-strict-optional *parsers tests

    - name: Test with `pytest`
      run: |
        python -m pytest -sv tests
